// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG } from './config';

// Use config from our manual config file to avoid Lovable env var override
const SUPABASE_URL = SUPABASE_CONFIG.url;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_CONFIG.anonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
