// Manual Supabase configuration - not auto-generated by Lovable
// This file provides the correct JWT anon key for the REST API

export const SUPABASE_CONFIG = {
  url: 'https://hnezenoxdwanofigtqdg.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZXplbm94ZHdhbm9maWd0cWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3ODgyMTIsImV4cCI6MjA4OTM2NDIxMn0.Q_juBkS0ZLsdd2irQYKeglr1Qb105xEm_DPSfPJDYYA',
};
